/* Do not edit this file! It is generated automatically by make_symbol.py */

char* global_kernel_version[] = 
{
	"#32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017",
	"#1 SMP Tue Feb 19 16:53:04 IST 2019",
};

struct symbol_table_struct global_symbol_table_array[] =
{
	/* #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 */
	{
		{
			{"_text", 0xffffffff81000000},
			{"syscall_return_slowpath", 0xffffffff81003ad0},
			{"do_int80_syscall_32", 0xffffffff81003bf0},
			{"do_fast_syscall_32", 0xffffffff81003cb0},
			{"mce_timer_delete_all", 0xffffffff81045e20},
			{"mce_cpu_restart", 0xffffffff81047ed0},
			{"walk_system_ram_range", 0xffffffff8108efe0},
			{"commit_creds", 0xffffffff810ab670},
			{"wake_up_new_task", 0xffffffff810b5a20},
			{"free_module", 0xffffffff811160f0},
			{"ftrace_module_init", 0xffffffff81157090},
			{"proc_flush_task", 0xffffffff812bf9e0},
			{"secure_ipv4_port_ephemeral", 0xffffffff817a5c10},
			{"secure_dccpv6_sequence_number", 0xffffffff817a5e50},
			{"netif_rx_internal", 0xffffffff817af7c0},
			{"__netif_receive_skb_core", 0xffffffff817b0310},
			{"netif_receive_skb_internal", 0xffffffff817b0de0},
			{"__ip_select_ident", 0xffffffff817f0540},
			{"entry_SYSCALL_64", 0xffffffff818d3e50},
			{"_etext", 0xffffffff818d9029},
			{"__start___ex_table", 0xffffffff818d9230},
			{"__stop___ex_table", 0xffffffff818dc50c},
			{"__start_rodata", 0xffffffff81a00000},
			{"__end_rodata", 0xffffffff81dbc000},
			{"tasklist_lock", 0xffffffff81e050c0},
			{"init_level4_pgt", 0xffffffff81e09000},
			{"check_interval", 0xffffffff81e2a848},
			{"modules", 0xffffffff81e882d0},
			{"init_mm", 0xffffffff81e9f9c0},
			{"logbuf_lock", 0xffffffff822467ac},
		},
	},
	/* #1 SMP Tue Feb 19 16:53:04 IST 2019 */
	{
		{
			{"_text", 0xffffffff81000000},
			{"syscall_return_slowpath", 0xffffffff81003ad0},
			{"do_int80_syscall_32", 0xffffffff81003bf0},
			{"do_fast_syscall_32", 0xffffffff81003cb0},
			{"mce_timer_delete_all", 0xffffffff81045c20},
			{"mce_cpu_restart", 0xffffffff81047d00},
			{"walk_system_ram_range", 0xffffffff8108ee50},
			{"commit_creds", 0xffffffff810ab300},
			{"wake_up_new_task", 0xffffffff810b5b00},
			{"free_module", 0xffffffff81116b20},
			{"ftrace_module_init", 0xffffffff81157ac0},
			{"proc_flush_task", 0xffffffff812bfd20},
			{"secure_ipv4_port_ephemeral", 0xffffffff81786b90},
			{"secure_dccpv6_sequence_number", 0xffffffff81786e80},
			{"netif_rx_internal", 0xffffffff817904f0},
			{"__netif_receive_skb_core", 0xffffffff81791070},
			{"netif_receive_skb_internal", 0xffffffff81791b50},
			{"__ip_select_ident", 0xffffffff817d1390},
			{"entry_SYSCALL_64", 0xffffffff818b4c50},
			{"_etext", 0xffffffff818b9e2b},
			{"__start___ex_table", 0xffffffff818ba030},
			{"__stop___ex_table", 0xffffffff818bd2f4},
			{"__start_rodata", 0xffffffff81a00000},
			{"__end_rodata", 0xffffffff81dbb000},
			{"tasklist_lock", 0xffffffff81e050c0},
			{"init_level4_pgt", 0xffffffff81e09000},
			{"check_interval", 0xffffffff81e2a688},
			{"modules", 0xffffffff81e87ed0},
			{"init_mm", 0xffffffff81e9f2a0},
			{"logbuf_lock", 0xffffffff8221c60c},
		},
	},
};

